services:
  - type: web
    name: arjuna-ai
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_VAPI_PUBLIC_KEY
        value: 40e7ab26-af43-4e5f-a7e3-6db1e781bdc9
      - key: NEXT_PUBLIC_VAPI_ASSISTANT_ID_PRIMARY
        sync: false
      - key: NEXT_PUBLIC_VAPI_ASSISTANT_ID_SECONDARY
        sync: false
      - key: VAPI_PRIVATE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false