services:
  - type: web
    name: arjuna-ai
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_VAPI_PUBLIC_KEY
        sync: false
      - key: NEXT_PUBLIC_VAPI_ASSISTANT_ID
        sync: false
      - key: VAPI_PRIVATE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false