import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import SessionWrapper from "../components/SessionWrapper";
import LayoutWrapper from "../components/LayoutWrapper";
import FloatingYantra from "../components/FloatingYantra";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-white dark:bg-gray-900 text-gray-900 dark:text-white transition-colors`}
      >
        
        <SessionWrapper>
           <LayoutWrapper>
        {children}
        </LayoutWrapper>
        </SessionWrapper>
        <FloatingYantra />
        <Analytics />
      </body>
    </html>
  );
}
